
dist: trusty
sudo: required
before_install:
language: python
notifications:
  email:
    recipients:
      - mailme@mikkokotila.com
    on_success: never
    on_failure: always
python:
 - '3.6'

script:
 - echo

deploy:
  provider: pypi
  user: "mikkokotila"
  password:
    secure: "riqFFcVCp3d2U5o/ly66JoM6NvyplyFKfhl8EB4bpyZRv13u1pk59b62435aq49rYVOlGy7i8V4Z+y7GPx+gxTrNfz8SKKfQSRmgEhQNmGmV7lY0KKDh5e7ud9YvH3gpZnh9j3Ke9NLQtIUUfRcGe3w2kmHsyuLQ5W7AbppWPXvaYtyyVvcOJnSZmR6B+MsZF9wRBWJltQExRxSQWsh6Lh3j9Uy9gL3XkFq1jRAnHy1Phmvlm/0amZI+vjmtKICmbPVac5OdGRLDj4Ed7oLz1o2fxmLKJoMbIr4yG46UBt3VcarOUk/Vm1i02KKdFhpRLK8XyfXtnaZ61Tfez6oCd1LrDCgzwlZo7U+o+8IgzPTjMSNvA1XyhlSfMRwhgpIAvwojke2JAvBpUeud0Z8u7+HyqMKlojPvKNs+6JQYBV8nOUiPW3+QAyd/jjPb+mciNdB/fgwGNcVR+Z/OR9ZziR1XDlQ+nuDCGecIlf7tEOCLhBzJwl/HLkVAUiDwIT4Qj8UkFuGbCjvKH8mu2Tk2FZLhAFbN6jpVQLsBGwXwJoEou5yNY0toPQ0kARLuxAMyC2okGHPsJbmVk9cNKVZA6tIz37eK4zP+c+sjH0U1SYIzw+NXTcNUqW+vI9LVjgVkm0nJxIeixhI1i99u4C4cN78weyqTTXJ2VL5zJXCqePw="
  on:
    branch: production
